
ARG ARCH
ARG PACKAGE
ARG TAG

RUN apt-get update && apt-get -y install inetutils-ping jq bc curl socat

COPY $PACKAGE/$PACKAGE-$TAG-$ARCH /usr/local/bin/$PACKAGE
COPY util/hex2string-$ARCH /usr/local/bin/hex2string
COPY util/string2hex-$ARCH /usr/local/bin/string2hex
COPY scripts/* /usr/local/bin/

WORKDIR /

