
ENV LC_ALL C
ENV DEBIAN_FRONTEND noninteractive
ENV DEBCONF_NONINTERACTIVE_SEEN true

MAINTAINER <datajerk@gmail.com>

RUN apt-get update -y && apt-get -y install python-pip

RUN pip install python-swiftclient

